config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls')),
    path('users/', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # to show avatars, also in settings

mailings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailings.views import MessageListView, MessageDetailView, MessageUpdateView, MessageDeleteView, MessageCreateView, \
    LogsListView, BlogDeleteView, BlogCreateView, BlogListView, BlogUpdateView, BlogDetailView, main_page
from mailings.views import ClientListView, ClientDetailView, ClientUpdateView, ClientCreateView, ClientDeleteView
from mailings.views import SettingsListView, SettingsCreateView

app_name = 'mailings'


urlpatterns = [
    path('', cache_page(60)(main_page), name='main_page'),
    path('main/', cache_page(60)(main_page), name='main_page'),

    path('messages/', MessageListView.as_view(), name='all_messages'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('create/', MessageCreateView.as_view(), name='create_message'),
    path('update/<int:pk>/', MessageUpdateView.as_view(), name='update_message'),
    path('delete/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),

    path('clients/', ClientListView.as_view(), name='all_clients'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('update_client/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('delete_client/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),

    path('settings/', SettingsListView.as_view(), name='all_settings'),
    path('create_settings', SettingsCreateView.as_view(), name='create_settings'),

    path('logs/', LogsListView.as_view(), name='all_logs'),

    path('create-blog/', BlogCreateView.as_view(), name='create_blog'),
    path('blog/', cache_page(60)(BlogListView.as_view()), name='read_blog'),
    path('update-blog/<int:pk>/', BlogUpdateView.as_view(), name='update_blog'),
    path('delete-blog/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),
    path('view-blog/<int:pk>/', BlogDetailView.as_view(), name='view_blog'),
]

users/urls.py
from django.contrib.auth import logout

from django.urls import path
from django.contrib.auth.views import LoginView

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, logout_view

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/newpassword', generate_new_password, name='generate_new_password'),

]

mailings/models.py
from django.db import models


class Client(models.Model):
    name = models.CharField(max_length=150, verbose_name='имя')
    fathers_name = models.CharField(max_length=150, verbose_name='отчество', null=True, blank=True)
    surname = models.CharField(max_length=150, verbose_name='фамилия')
    email = models.CharField(max_length=150, verbose_name='email')
    comment = models.TextField(verbose_name='комментарий', null=True, blank=True)

    def __str__(self):
        return f'{self.name} {self.surname}: {self.email}'

    class Meta:
        verbose_name = "клиент"
        verbose_name_plural = "клиенты"
        ordering = ('surname',)


class Message(models.Model):
    subject = models.CharField(max_length=300, verbose_name="тема письма")
    body = models.TextField(verbose_name="тело письма")

    # settings = models.ForeignKey(Settings, on_delete=models.CASCADE, verbose_name="Настройки рассылки")

    def __str__(self):
        return f'{self.subject} : {self.body}'

    class Meta:
        verbose_name = "сообщение для рассылки"
        verbose_name_plural = "сообщения для рассылки"


class Settings(models.Model):

    FREQUENCY_CHOICES = [
        ('once_a_day', 'Once a Day'),
        ('once_a_week', 'Once a Week'),
        ('once_a_month', 'Once a Month'),
    ]

    STATUS_CHOICES = [
        ('completed', 'Completed'),
        ('created', 'Created'),
        ('started', 'Started'),
    ]

    mailing_time = models.DateTimeField(verbose_name="время рассылки", auto_now=True)
    periodicity = models.CharField(verbose_name="периодичность", max_length=20, choices=FREQUENCY_CHOICES, default='once_a_day')
    status = models.CharField(verbose_name="статус рассылки", max_length=20, choices=STATUS_CHOICES, default='created')

    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name="Клиент")
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение')

    def __str__(self):
        return f'Письмо отослано в {self.mailing_time} : {self.status}'

    class Meta:
        verbose_name = "настройка"
        verbose_name_plural = "настройки"


class Logs(models.Model):
    last_attempt = models.DateTimeField(verbose_name="Дата и время последней попытки")  # При типе данных DateTimeField возникает ошибка с записью в БД
    status = models.CharField(max_length=200, verbose_name="статус попытки", default='completed')
    response = models.CharField(max_length=200, verbose_name="ответ почтового сервера", null=True, blank=True)

    settings = models.ForeignKey(Settings, on_delete=models.CASCADE, verbose_name="Настройки рассылки")

    def __str__(self):
        return f'{self.last_attempt}'

    class Meta:
        verbose_name = "лог рассылки"
        verbose_name_plural = "логи рассылки"


class Blog(models.Model):
    title = models.CharField(max_length=300, verbose_name="заголовок")
    content = models.TextField(verbose_name='содержимое статьи')
    image = models.ImageField(upload_to='mailings/images/', verbose_name='изображение', null=True, blank=True)
    number_of_views = models.PositiveIntegerField(default=0, verbose_name="количество просмотров")
    date_of_publication = models.DateField(verbose_name='дата публикации')

    def __str__(self):
        return f'{self.title} -- {self.content}'

    class Meta:
        verbose_name = "блог"
        verbose_name_plural = "блоги"

mailings/views.py
from random import sample

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, reverse
from mailings.models import Message, Client, Settings, Logs, Blog
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


def main_page(request):

    total_messages_count = Message.objects.count()
    active_logs_count = Logs.objects.count()
    active_clients_count = Client.objects.count()

    all_blogs = Blog.objects.all()
    random_blogs = sample(list(all_blogs), min(3, all_blogs.count()))

    context = {
        'total_messages_count': total_messages_count,
        'active_logs_count': active_logs_count,
        'active_clients_count': active_clients_count,
        'random_blogs': random_blogs
    }

    return render(request, 'mailings/main_page.html', context)


class MessageListView(ListView):
    """ shows all messages"""
    model = Message
    template_name = 'mailings/message_list.html'


class MessageDetailView(DetailView):
    """ shows one item (mailing message)"""
    model = Message
    template_name = 'mailings/message_detail.html'


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """makes changes in the model Massage == UPDATE"""
    model = Message
    fields = ('subject', 'body', 'settings')
    template_name = 'mailings/message_form.html'

    def get_success_url(self):
        return reverse('mailings:main_page')


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """deletes one model of Message"""
    model = Message
    template_name = 'mailings/message_confirm_delete.html'

    def get_success_url(self):
        return reverse('mailings:main_page')


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = ('subject', 'body', 'settings')
    template_name = 'mailings/message_form.html'

    def get_success_url(self):
        return reverse('mailings:main_page')


class ClientListView(ListView):
    """ shows all clients"""
    model = Client
    template_name = 'mailings/client_list.html'


class ClientDetailView(DetailView):
    """ shows one item (one client)"""
    model = Client
    template_name = 'mailings/client_detail.html'


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """makes changes in the model Client == UPDATE"""
    model = Client
    fields = ('name', 'fathers_name', 'surname', 'email', 'comment')
    template_name = 'mailings/client_form.html'

    def get_success_url(self):
        return reverse('mailings:all_clients')


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ('name', 'fathers_name', 'surname', 'email', 'comment')
    template_name = 'mailings/client_form.html'

    def get_success_url(self):
        return reverse('mailings:all_clients')


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    """deletes one model of Client"""
    model = Client
    template_name = 'mailings/client_confirm_delete.html'

    def get_success_url(self):
        return reverse('mailings:all_clients')


class SettingsListView(ListView):
    """ shows all settings"""
    model = Settings
    template_name = 'mailings/settings_list.html'


class SettingsCreateView(LoginRequiredMixin, CreateView):
    model = Settings
    fields = ('periodicity', 'status', 'client', 'message')
    template_name = 'mailings/settings_form.html'

    def get_success_url(self):
        return reverse('mailings:all_settings')


class LogsListView(ListView):
    """ shows all logs"""
    model = Logs
    template_name = 'mailings/logs_list.html'


#  часть 2 - добавляем вьюшки для блога


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'image', 'date_of_publication')
    template_name = 'mailings/blog_form.html'

    def get_success_url(self):
        return reverse('mailings:read_blog')


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'content', 'image', 'date_of_publication')
    template_name = 'mailings/blog_form.html'

    def get_success_url(self):
        return reverse('mailings:read_blog')


class BlogListView(ListView):
    model = Blog
    template_name = 'mailings/blog_list.html'


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog
    template_name = 'mailings/blog_detail.html'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_of_views += 1
        self.object.save()
        return self.object


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    template_name = 'mailings/blog_confirm_delete.html'

    def get_success_url(self):
        return reverse('mailings:read_blog')

mailings/templates/mailings/base.html
{% load static %}

<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <title>Сервис управления рассылками</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/pricing/">

    

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="{% static 'mailings/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static 'mailings/pricing.css' %}" rel="stylesheet">
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="check" viewBox="0 0 16 16">
    <title>Check</title>
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  </symbol>
</svg>

<div class="container py-3">
  <header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
        <span class="fs-4">Сервис управления рассылками</span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'mailings:all_messages' %}">Pассылки</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'mailings:all_clients' %}">Клиенты</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'mailings:all_settings' %}">Настройки</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'mailings:all_logs' %}">Логи</a>

        {% if user.is_authenticated %}
          <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:logout' %}">Выйти</a>
          <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:profile' %}">Профиль</a>
        {% else %}
          <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:login' %}">Войти</a>
          <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}

        <a class="py-2 link-body-emphasis text-decoration-none" href="{% url 'mailings:read_blog' %}">BLOG</a>
      </nav>
    </div>

    {% block content %}

    {% endblock %}


<!--  POSSIBLY HERE WILL BE PLACE FOR YOUR FUTURE BLOCKS-->


  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-6 col-md">
        <h5>Клиенты</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="{% url 'mailings:all_clients' %}">Просмотреть</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Рассылка (настройки)</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="{% url 'mailings:all_settings' %}">Просмотреть</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="{% url 'mailings:create_settings' %}">Создать</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="{% url 'mailings:all_logs' %}">Отчет о рассылках (логи)</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Блог</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="{% url 'mailings:read_blog' %}">Все записи</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>
<script src="{% static 'mailings/dist/js/bootstrap.bundle.min.js' %}" ></script>

    </body>
</html>

mailings/templates/mailings/blog_detail.html
{% extends 'mailings/base.html' %}
{% load static %}

{% block content %}

<div class="row mb-2">

    <div class="col-md-6 mb-4">
        <div class="row g-0 border rounded overflow-hidden flex-md-row shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <h3 class="mb-0">{{ blog.title }}</h3>
                <div class="mb-1 text-body-secondary">{{ blog.date_of_publication }}</div>
                <p class="card-text mb-auto">{{ blog.content }}</p>
                <div class="mb-1 text-body-secondary">Number of views: {{ blog.number_of_views }}</div>
                <a class="btn btn-outline-primary" href="{% url 'mailings:update_blog' blog.pk%}">Изменить</a>
                <a class="btn btn-outline-success" href="{% url 'mailings:create_blog' %}">Добавить</a>
                <a class="btn btn-outline-danger" href="{% url 'mailings:delete_blog' blog.pk%}">Удалить</a>

            </div>
            <div class="col-auto d-none d-lg-block">
                {% if blog.image %}
                <img src="{{ blog.image.url }}" alt="Blog Image" width="200" height="250">
                {% else %}
                <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#55595c"/>
                    <text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
                </svg>
                {% endif %}
            </div>
        </div>
    </div>
</div>


{% endblock %}

mailings/templates/mailings/blog_list.html
{% extends 'mailings/base.html' %}
{% load static %}

{% block content %}

<div class="row mb-2">
    {% for blog in object_list %}
    <div class="col-md-6 mb-4">
        <div class="row g-0 border rounded overflow-hidden flex-md-row shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <h3 class="mb-0">{{ blog.title }}</h3>
                <div class="mb-1 text-body-secondary">{{ blog.date_of_publication }}</div>
                <p class="card-text mb-auto">{{ blog.content|slice:":150" }}</p>
                <a href="{% url 'mailings:view_blog' blog.pk %}" class="icon-link gap-1 icon-link-hover stretched-link">
                    Continue reading
                    <svg class="bi"><use xlink:href="#chevron-right"/></svg>
                </a>
            </div>
            <div class="col-auto d-none d-lg-block">
                {% if blog.image %}
                <img src="{{ blog.image.url }}" alt="Blog Image" width="200" height="250">
                {% else %}
                <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#55595c"/>
                    <text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
                </svg>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}

mailings/templates/mailings/client_detail.html
{% extends 'mailings/base.html' %}
{% load static %}

{% block content %}

<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        <div class="col">

            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">{{ client.name }} {{ client.surname }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>{{ client.email }}</li>
                        <li>{{ client.comment }}</li>
                    </ul>
                    <a class="w-100 btn btn-lg btn-success" href="{% url 'mailings:update_client' client.pk%}">Изменить</a>
                    <a class="w-100 btn btn-lg btn-primary" href="{% url 'mailings:create_client' %}">Добавить нового</a>
                    <a class="w-100 btn btn-lg btn btn-danger" href="{% url 'mailings:delete_client' client.pk%}">Удалить</a>
                    <a class="w-100 btn btn-lg btn btn btn-warning" href="#">Рассылки ПОТОМ</a>
                </div>
            </div>

        </div>
    </div>
</main>

{% endblock %}

mailings/templates/mailings/main_page.html
{% extends 'mailings/base.html' %}
{% load static %}

{% block content %}

<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal text-body-emphasis">Сервис управления рассылками</h1>
</div>
</header>

<main>
    <div class="row row-cols-1 row-cols-md-3 mb-6 text-center">
        <div class="col-md-12">

            <div class="card mb-4 rounded-6 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Вся информация о рассылках</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Общее количество рассылок: {{ total_messages_count }}</li>
                        <li>Количество проведенных активных рассылок: {{ active_logs_count }}</li>
                        <li>Общее количество активных клиентов: {{ active_clients_count }}</li>
                    </ul>
                    <a class="w-100 btn btn-lg btn-success" href="{% url 'mailings:all_messages' %}">Просмотреть рассылки</a>
                </div>
            </div>

            <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
                <h2 class="display-4 fw-normal text-body-emphasis">У нас так же есть блог...</h2>
            </div>
        </div>
            <div class="col-md-12">
            <div class="card mb-4 rounded-6 shadow-sm">
                {% for blog in random_blogs %}
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">{{ blog.title }}</h4>
                </div>
                <div class="card-body">
                        <p>{{ blog.content|slice:":150" }}</p>
                        <a class="w-100 btn btn-outline-success" href="{% url 'mailings:view_blog' blog.pk %}">Просмотреть</a>
                </div>
                {% endfor %}
            </div>
       </div>
    </div>
</main>

<!--<div class="pricing-header p-3 pb-md-4 mx-auto text-center">-->
<!--      <h2 class="display-4 fw-normal text-body-emphasis">У нас так же есть блог...</h2>-->
<!--</div>-->


{% endblock %}

mailings/templates/mailings/message_detail.html
{% extends 'mailings/base.html' %}
{% load static %}

{% block content %}

<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        <div class="col">

            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">{{ message.subject }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>{{ message.body }}</li>
                    </ul>
                    <a class="w-100 btn btn-lg btn-success" href="{% url 'mailings:update_message' message.pk%}">Изменить</a>
                    <a class="w-100 btn btn-lg btn btn-danger" href="{% url 'mailings:delete_message' message.pk%}">Удалить</a>
                    <a class="w-100 btn btn-lg btn-primary" href="{% url 'mailings:create_message' %}">Создать новый</a>
                </div>
            </div>

        </div>
    </div>
</main>

{% endblock %}